apiVersion: "v1"
kind: "Template"
metadata:
  name: "front-generator-s2i"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: front-generator
    name: front-generator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: front-generator:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/obsidian-toaster/obsidian-toaster.github.io.git
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: centos/nodejs-4-centos7
    triggers:
    - github:
        secret: BCedrGCnc2IWefYxQ9sr
      type: GitHub
    - generic:
        secret: 0nqmEYlp7o6Sx_rUNIpq
      type: Generic
    - type: ConfigChange
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: front-generator
    name: front-generator
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: front-generator
    name: front-generator
  spec:
    replicas: 1
    selector:
      app: front-generator
      deploymentconfig: front-generator
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: front-generator
          deploymentconfig: front-generator
      spec:
        containers:
        - image: front-generator:latest
          imagePullPolicy: Always
          name: front-generator
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - front-generator
        from:
          kind: ImageStreamTag
          name: front-generator:latest
          namespace: default
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: front-generator
    name: front-generator
  spec:
    clusterIP:
    portalIP:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: front-generator
      deploymentconfig: front-generator
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: front-generator
    name: front-generator
  spec:
    host:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: front-generator
      weight: 100
