apiVersion: v1
kind: Template
metadata:  
  name: launcher-nginx
parameters:
- name: IMAGE
  value: registry.devshift.net/openshiftio/launchpad-nginx
  required: true
- name: IMAGE_TAG
  value: latest
  required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      run: launcher-nginx
    name: launcher-nginx
  spec:
    replicas: 1
    selector:
      run: launcher-nginx
    strategy:
      resources:
        requests:
          cpu: 20m
          memory: 20Mi
        limits:
          cpu: 200m
          memory: 200Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          run: launcher-nginx
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: launcher-nginx
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /wizard
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /wizard
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 20
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: launcher-nginx
    annotations:
      service.alpha.openshift.io/dependencies: "[{\"name\":\"launcher-frontend\",\"namespace\":\"\",\"kind\":\"Service\"},{\"name\":\"launcher-backend\",\"namespace\":\"\",\"kind\":\"Service\"}]"
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: launcher-nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata: 
    name: launcher-nginx
  spec:
    to:
      kind: Service
      name: launcher-nginx
      weight: 100
    wildcardPolicy: None
  status: {}
