kind: Template
apiVersion: v1
metadata:
  name: backend-generator-s2i
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      group: io.obsidian
      project: generator-backend
      provider: obsidian
      version: 1.0.0-SNAPSHOT
    name: generator-backend
  spec:
    tags:
    - annotations: {}
      from:
        kind: DockerImage
        name: 172.30.92.36:5000/obsidian/generator-backend:latest
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      group: io.obsidian
      project: generator-backend
      provider: obsidian
      version: 1.0.0-SNAPSHOT
    name: generator-backend-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: generator-backend:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/obsidian-toaster/generator-backend.git
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: fabric8/s2i-java:1.3
        incremental: true
    triggers:
    - github:
        secret: BCedrGCnc2IWefYxQ9sr
      type: GitHub
    - generic:
        secret: 0nqmEYlp7o6Sx_rUNIpq
      type: Generic
    - type: ConfigChange
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      group: io.obsidian
      project: generator-backend
      provider: obsidian
      version: 1.0.0-SNAPSHOT
    name: generator-backend
  spec:
    replicas: 1
    selector:
      group: io.obsidian
      project: generator-backend
      provider: obsidian
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 10800
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=generator-backend&var-version=1.0.0-SNAPSHOT
        creationTimestamp: null
        labels:
          group: io.obsidian
          project: generator-backend
          provider: obsidian
          version: 1.0.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: AB_JOLOKIA_OFF
            value: "true"
          - name: JAVA_APP_DIR
            value: /deployments
          - name: AB_OFF
            value: "true"
          image: 172.30.92.36:5000/obsidian/generator-backend:latest
          imagePullPolicy: IfNotPresent
          name: wildfly-swarm
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wildfly-swarm
        from:
          kind: ImageStreamTag
          name: generator-backend:latest
          namespace: obsidian
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      group: io.obsidian
      project: generator-backend
      provider: obsidian
      version: 1.0.0-SNAPSHOT
    name: generator-backend
  spec:
    ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      group: io.obsidian
      project: generator-backend
      provider: obsidian
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: generator-backend
      group: io.obsidian
      project: generator-backend
      provider: obsidian
      version: 1.0.0-SNAPSHOT
    name: generator-backend
  spec:
    tls:
      termination: passthrough
    to:
      kind: Service
      name: generator-backend
      weight: 100
