openapi: 3.0.0
servers:
- url: http://api-creator-backend.devtools-dev.ext.devshift.net/
  description: Development server
- url: http://localhost:8081
  description: Local Development

info:
  version: "1.0.0"
  title: Launcher Creator Backend API
  description: >-
    This document defines the REST endpoints exposed by the
    launcher-creator-backend component

security:
- application:
  - read
  - write

paths:
  /runtimes:
    get:
      summary: Returns the available Runtimes
      security: []
      description: >-
        This endpoint returns all known Runtimes
      tags:
      - runtimes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runtime'
        '404':
          description: Not Found
  /capabilities:
    get:
      summary: Returns the available Capabilities
      security: []
      description: >-
        This endpoint returns all known Capabilities
      tags:
      - capabilities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Capability'
        '404':
          description: Not Found
  /zip:
    get:
      summary: Returns a ZIP containing a generated project
      security: []
      description: >-
        This endpoint returns all ZIP containing code that was
        generated using the specified Capabilities
      tags:
      - zip
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
        description: The application name to use for the project
      - name: runtime
        in: query
        required: true
        schema:
          type: string
        description: The runtime to use for the project
      - name: capability
        in: query
        required: true
        schema:
          type: array
          items:
            type: object
            properties:
              module:
                type: string
        description: The capabilities to add to the project
      responses:
        '200':
          description: OK
          content:
            application/zip: {}
        '404':
          description: Not Found
  /launch:
    post:
      summary: Pushes a generated project to GitHub and OpenShift
      security:
      - bearerAuth: []
      description: >-
        This endpoint pushes code that was generated using the specified
        Capabilities to a user's GitHub and OpenShift accounts
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  description: The application name to use for the project
                  type: string
                runtime:
                  description: The runtime to use for the project
                  type: string
                capability:
                  description: The capabilities to add to the project
                  type: array
                  items:
                    type: object
                    properties:
                      module:
                        type: string
              required:
              - name
              - runtime
              - capability
      responses:
        '200':
          description: OK
        '404':
          description: Not Found

components:
  schemas:
    Runtime:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        icon:
          type: string
        metadata:
          type: object

    Capability:
      type: array
      items:
        type: object
        properties:
          module:
            type: string
          name:
            type: string
          description:
            type: string
          props:
            type: object

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
