kind: Template
apiVersion: v1
parameters:
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN
  displayName: OpenShift token
  description: OpenShift token (leave empty when using Keycloak with OpenShift as an Identity Provider or user/password above)
  value:
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: launcher
  data:
    launcher.missioncontrol.openshift.clusters.subscription.token:
    launcher.missioncontrol.openshift.token: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN}

