kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: launcher-frontend
  spec:
    to:
      kind: Service
      name: launcher-frontend
      weight: 100
    wildcardPolicy: None
  status: {}

