apiVersion: v1
kind: Template
metadata:  
  name: launchpad-configmapcontroller
parameters:
- name: IMAGE
  value: fabric8/configmapcontroller
  required: true
- name: IMAGE_TAG
  value: 2.3.7
  required: true
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      service: configmapcontroller
    name: configmapcontroller
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      service: configmapcontroller
    name: configmapcontroller-edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: configmapcontroller
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: configmapcontroller
    name: configmapcontroller
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      service: configmapcontroller
    strategy:
      rollingParams:
        timeoutSeconds: 7200
      type: Rolling
    template:
      metadata:
        labels:
          service: configmapcontroller
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: ${IMAGE}:${IMAGE_TAG}
          name: configmapcontroller
        serviceAccountName: configmapcontroller
    triggers:
    - type: ConfigChange

